name: Setup Sample Data on Deploy Branch

on:
  push:
    branches:
      - deploy

jobs:
  "setup-sample-data":
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove existing database
        run: npm remove_db.ts

      - name: Insert sample data
        run: npm insert_sample_db.ts